# -*- coding: utf-8 -*-
"""ML de clasificación de riesgo de salud mental.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMGsiwOiHEAL2u9FMmfpCbjw6HN9N1mh

Se realizó el siguiente proyecto de clasificación del riesgo de salud mental tomando como datos el dataset brindado por: https://www.kaggle.com/datasets/alamshihab075/mental-health-dataset

este conjunto de datos recopila   información autodeclarada por individuos para examinar cómo la trayectoria profesional, los hábitos laborales, los patrones de estrés y los mecanismos personales de afrontamiento influyen en la salud mental y el bienestar emocional. Los datos ponen de relieve la compleja relación entre el compromiso laboral, los hábitos de vida y la resiliencia mental.
El objetivo es realizar machine learning que sea capaz de clasificar con alta precisión el riesgo de desarrollar historial de salud mental y asi identificar el factor de riesgo principal
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "Mental Health dataset1.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "alamshihab075/mental-health-dataset",
  file_path,
)

print("First 5 records:", df.head())

df['MentalHealthHistory'] = df['MentalHealthHistory'].map({'Yes': 1, 'No': 0}).fillna(0).astype(int)

# Variables Binarias: Mapeo de Sí/No/Tal vez a 1/0
df['SelfEmployed'] = df['SelfEmployed'].map({'Yes': 1, 'No': 0}).fillna(0).astype(int)
df['FamilyHistory'] = df['FamilyHistory'].map({'Yes': 1, 'No': 0}).fillna(0).astype(int)
df['Treatment'] = df['Treatment'].map({'Yes': 1, 'No': 0}).fillna(0).astype(int)

"""Se convierten los datos a binario para su uso en Machine Learning"""

day = df['DaysIndoors']

conteo_valores = day.value_counts()
print(conteo_valores)

days_indoor_order = {
    'Go out Every day': 0,
    '1-14 days': 1,
    '15-30 days': 2,
    '31-60 days days': 3,
    'More than 2 months': 4,
}

df['Aislamiento_Ordinal'] = df['DaysIndoors'].map(days_indoor_order).fillna(0).astype(int)
df = df.drop('DaysIndoors', axis=1)

"""Se convierte en escala numérica las variables de texto para interpretar la severidad del aislamiento"""

print("\nDistribución de la Variable Objetivo:")
print(df['MentalHealthHistory'].value_counts(normalize=True))

plt.figure(figsize=(10, 5))
sns.countplot(data=df, x='IncreasingStress', hue='MentalHealthHistory', palette='coolwarm')
plt.title('Relación entre Aumento de Estrés y Crisis de Salud Mental')
plt.xlabel('Nivel de Aumento de Estrés')
plt.ylabel('Conteo de Individuos')
plt.show()

"""El gráfico de barras confirma el fuerte desequilibrio de clases presente en el conjunto de datos , donde la Clase 0 domina en todas las categorías de estrés. A pesar de esto, se observa una relación visible: la categoría 'Yes' en 'Nivel de Aumento de Estrés' concentra la mayor cantidad de casos positivos , lo que valida la inclusión de esta variable en el modelado."""

print("\n--- FASE 2: Ingeniería de Características y Preprocesamiento ---")

X = df.drop('MentalHealthHistory', axis=1)
y = df['MentalHealthHistory']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

nominal_features = ['Gender', 'Country', 'Occupation', 'HabitsChange', 'IncreasingStress']
numeric_features = ['Aislamiento_Ordinal']
binary_features = ['SelfEmployed', 'FamilyHistory', 'Treatment']

preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False), nominal_features),
        ('scaler', StandardScaler(), numeric_features),
        ('passthrough', 'passthrough', binary_features)
    ],
    remainder='drop'
)

print("Preprocesador de características definido.")

print("\n--- FASE 3: Modelado y Entrenamiento ---")

# 1. Regresión Logística
log_reg_model = Pipeline(steps=[('preprocessor', preprocessor),
                                 ('classifier', LogisticRegression(random_state=42, solver='liblinear'))])

# 2. Random Forest
rf_model = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))])

# 3. Support Vector Classifier
svc_model = Pipeline(steps=[('preprocessor', preprocessor),
                            ('classifier', LinearSVC(random_state=42))])

models = {
    'Regresión Logística': log_reg_model,
    'Random Forest': rf_model,
    'SVC': svc_model
}

for name, model in models.items():
    print(f"Entrenando modelo: {name}...")
    model.fit(X_train, y_train)
    print(f"Modelo {name} entrenado.")

def evaluate_model_ajustado(model, X_test, y_test, name, custom_threshold=0.3):
    """
    Evalúa el modelo y retorna las métricas.
    Aplica un umbral personalizado si el modelo no es Random Forest.
    """

    classifier = model.named_steps['classifier']
    X_processed = model.named_steps['preprocessor'].transform(X_test)

    if hasattr(classifier, 'predict_proba'):
        y_scores = classifier.predict_proba(X_processed)[:, 1]
    elif hasattr(classifier, 'decision_function'):
        decision_scores = classifier.decision_function(X_processed)
        y_scores = 1 / (1 + np.exp(-decision_scores))
    else:
        y_scores = np.zeros(len(y_test))

    if name == 'Random Forest':
        y_pred = classifier.predict(X_processed)
    else:
        y_pred = (y_scores >= custom_threshold).astype(int)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_scores)

    metrics = {
        'Modelo': name,
        'Accuracy': f"{accuracy:.4f}",
        'Precision': f"{precision:.4f}",
        'Recall': f"{recall:.4f}",
        'F1-Score': f"{f1:.4f}",
        'AUC': f"{auc:.4f}"
    }
    return metrics

print("\n--- FASE 4: Evaluación de Rendimiento (Umbral Ajustado) ---")

results = []
UMBRAL_AJUSTADO = 0.3

for name, model in models.items():
    metrics = evaluate_model_ajustado(model, X_test, y_test, name, custom_threshold=UMBRAL_AJUSTADO)
    results.append(metrics)

results_df = pd.DataFrame(results).set_index('Modelo')
print(f"Tabla de Resultados de Clasificación en el Conjunto de Prueba (Umbral Lineal={UMBRAL_AJUSTADO}):")
print(results_df)

# --- FASE 5: Interpretación del Modelo y Factores de Riesgo ---

rf_classifier = rf_model.named_steps['classifier']
feature_importances = rf_classifier.feature_importances_

feature_names = []
for name, transformer, cols in preprocessor.transformers_:
    if name == 'onehot':
        feature_names.extend(transformer.get_feature_names_out(input_features=cols))
    elif name in ['scaler', 'passthrough']:
        feature_names.extend(cols)

import pandas as pd
importance_df = pd.DataFrame({
    'Característica': feature_names,
    'Importancia': feature_importances
}).sort_values(by='Importancia', ascending=False)

print("\nTop 10 Factores de Riesgo (Feature Importance):")
print(importance_df.head(10).to_markdown(index=False))

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(12, 7))
sns.barplot(x='Importancia', y='Característica', data=importance_df.head(10), palette='viridis', hue='Característica', legend=False)
plt.title('Importancia de las 10 Características Más Predictivas (Random Forest)')
plt.xlabel('Importancia Relativa (Peso en la Predicción)')
plt.ylabel('Característica')
plt.show()

"""Conclusiones:

Mediante un  proceso de Ingeniería de Características y modelado comparativo, este proyecto de Machine Learning ha culminado en la selección de un Random Forest como el modelo predictivo óptimo para la clasificación del riesgo de historial de salud mental.

El Random Forest demostró ser el modelo más robusto al capturar las complejas relaciones no lineales del dataset y manejar el desequilibrio de clases de manera efectiva.

El resultado más significativo para el negocio se extrajo del análisis de Importancia de Características : el Nivel de Aislamiento ( Aislamiento_Ordinal) fue identificado como el factor de riesgo principal y dominante con una Importancia aproximada del 38%. Esta conclusión fundamental ofrece una dirección clara para cualquier estrategia de intervención: las iniciativas futuras para mitigar el riesgo deben priorizar la reducción del aislamiento, así como el monitoreo del Cambio de Hábitos y el Aumento de Estrés , ya que estos son los siguientes factores de mayor peso predictivo.
"""